# Generated by Django 4.1 on 2022-09-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzasize',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vineyear',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
