# Generated by Django 4.1 on 2022-09-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_pizzasize_is_user_vineyear_is_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VineYear',
            new_name='Pizza_Size',
        ),
        migrations.RenameModel(
            old_name='PizzaSize',
            new_name='Vine_Year',
        ),
    ]
