# Generated by Django 4.1 on 2022-09-04 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('site_url', models.CharField(max_length=256)),
                ('Количество звезд', models.IntegerField()),
                ('Количество комнат', models.IntegerField()),
                ('pizza', models.ManyToManyField(to='products.pizza')),
                ('vine', models.ManyToManyField(to='products.vine')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('is_open', models.BooleanField(default=True)),
                ('hotel_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dessan_django.hotel')),
            ],
        ),
    ]
