# Generated by Django 4.1 on 2022-09-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dessan_django', '0002_hotel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
