# Generated by Django 4.1 on 2022-09-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dessan_django', '0003_alter_hotel_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='picture',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
